language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools # Update preinstalled tools from revision 24.0.2 to 24.4.1
    - build-tools-25.0.2 # Match build-tools version used in build.gradle
    - platform-tools # Update platform-tools to revision 25.0.3+
    - tools # Update tools from revision 24.4.1 to 25.2.5
    - android-23
    - android-25
    - sys-img-armeabi-v7a-google_apis-23

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk-24.0.2
    - TOOLS=${ANDROID_HOME}/tools
    - TEMP=${ANDROID_HOME}/:${TOOLS}/:${TOOLS}/bin:${TOOLS}/emulator:${ANDROID_HOME}/platform-tools
    - PATH=${TEMP}:${PATH}
    - EMULATOR="system-images;android-23;google_apis;armeabi-v7a"

before_install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg # Avoid warning
  - sdkmanager --list || true
  - sdkmanager --list --help || true
  - sdkmanager --uninstall "system-images;android-15;default;armeabi-v7a"
  # ...
  #  - echo yes | sdkmanager "tools"
  #  - echo yes | sdkmanager "platforms;android-23"
  #  - echo yes | sdkmanager "platforms;android-25"
  - echo yes | sdkmanager "extras;android;m2repository"
  - echo yes | sdkmanager "extras;google;m2repository"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
  #  - echo yes | sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
  - echo "$PATH"
  - ls -Al
